import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "../component/header";
import HomePage from "../component/homePage";
import { useEffect, useRef, useState } from "react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tourisa</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className={styles.main}>
        <HomePage />
      </main>
    </div>
  );
};

export default Home;
