import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Header from "../component/header";
import HomePage from "../component/homePage";
import { useEffect, useRef, useState } from "react";
import { statesArr, districtsArr } from "../data/states";
import Upload from "../component/upload";
import {
  collection,
  doc,
  updateDoc,
  query,
  where,
  onSnapshot,
} from "firebase/firestore";

import { db } from "../fireb/firebApp";

const Home: NextPage = () => {
  const [plans, setPlans] = useState(["huhu"]);
  const [districts, setDistricts] = useState(districtsArr[0]);
  const stateRef = useRef<HTMLSelectElement | null>(null);
  const districtRef = useRef<HTMLSelectElement | null>(null);

  function stateSelect() {
    console.log(stateRef.current?.value);
    let v = stateRef.current?.value;
    let d = statesArr.findIndex((x) => {
      return x == v;
    });
    console.log(d);

    setDistricts([...districtsArr[d]]);
  }
  function search() {
    console.log(stateRef.current?.value);
    console.log(districtRef.current?.value);
    console.log(plans);
  }
  useEffect(() => {
    const unsub = onSnapshot(doc(db, "plans", "LA"), (doc) => {
      setPlans(doc.data());
      console.log(doc.data());
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Tourisa</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <HomePage />
      <main className={styles.main}>
        <label htmlFor='state'>State</label>
        <select ref={stateRef} onChange={stateSelect} name='state' id='state'>
          {statesArr.map((val, i) => {
            return (
              <option value={val} key={i}>
                {val}
              </option>
            );
          })}
        </select>
        <br />
        <label htmlFor='district'>District</label>

        <select ref={districtRef} name='dis' id='dis'>
          {districts.map((val, i) => {
            return (
              <option value={val} key={i}>
                {val}
              </option>
            );
          })}
        </select>
        <br />
        <button onClick={search}>Search</button>
        <hr />
        <hr />
        {/* {plans.map((val, i) => {
          return (
            <div key={i}>
              <h1></h1>
            </div>
          );
        })} */}
        <hr />
        <hr />
        <Upload />
      </main>
    </div>
  );
};

export default Home;
